### ISSUE TITLE
Python 2 Deprecation Plan

### ISSUE THREAD

**Issue by sethtroisi** [micheles/decorator#84]
Hey, I'm working on deleting Python 2 code in numpy/scipy, which includes a copy of decorator (yay!).

I see you mention full backwards support to python 2.6 in `src/tests/documentation.py`, but that seems to have been written ~5 years ago. With Python 2 no longer officially supported would you be interested in dropping Python 2 support? It looks like it's possible it would allow for the clean up of a few pieces of logic. I'm happy to help out if so.

**Comment by hugovk** [comment]
Python 3.2-3.4 are also EOL.

Here's the pip installs for Decorators for Humans from PyPI for February 2020:

| category | percent | downloads  |
|----------|--------:|-----------:|
| 2.7      |  37.23% |  5,556,658 |
| 3.6      |  31.31% |  4,674,275 |
| 3.7      |  20.61% |  3,076,252 |
| 3.5      |   5.47% |    816,134 |
| 3.8      |   3.20% |    477,122 |
| null     |   1.25% |    186,267 |
| 3.4      |   0.66% |     97,959 |
| 2.6      |   0.27% |     40,331 |
| 3.9      |   0.01% |      1,683 |
| 3.3      |   0.00% |        102 |
| 3.2      |   0.00% |          3 |
| Total    |         | 14,926,786 |

Source: `pip install -U pypistats && pypistats python_minor decorator --last-month`

**Comment by micheles** [comment]
Thank you Hugo, I was not aware of pypistats and these figures are really interesting. So Python 2.7 is  still dominating in the usage of decorator, I did not expect that. I had thought about dropping support for Python 2.7, since we are in 2020, but I have no strong reasons to do that and given such findings I am even more convinced that the strategy of doing nothing is the best one. If in a few years the stats will change I may change my mind.

**Comment by hugovk** [comment]
Here's how the 2/3 proportion has changed over the last 6 months:

![image](https://user-images.githubusercontent.com/1324225/76143144-6fbc2080-607d-11ea-9d35-44ea49c0e768.png)

https://pypistats.org/packages/decorator

**Comment by sethtroisi** [comment]
Their for considering, and thanks for the data hugo

**Comment by hugovk** [comment]
How about dropping 3.2, 3.3 and/or 3.4?

**Comment by micheles** [comment]
Based on the numbers of downloads I could, however on my part it is zero work to support such old versions; I would keep things as they are. It is true that at some moment travis will drop support for Python 3.4, so that version will not be tested anymore, like versions 3.0, 3.1, 3.2, 3.3 are not tested anymore, however, since the decorator module is very stable, it should keep working even for ancient releases. If not, I am sure somebody would protest since the module is so much used by other projects ;-)

**Comment by micheles** [comment]
One year has passed, and now I have released version 5 of the decorator module that drops support for Python < 3.5.
